#!/bin/bash
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PUBLIC="$SCRIPT_DIR/zshrc"
PRIVATE="/Users/jds/workspace/jds_private_config/zshrc_private/zshrc"
TARGET="$HOME/.zshrc"
GENERATED="$SCRIPT_DIR/zshrc_generated"
BACKUP_DIR="$SCRIPT_DIR/.zshrc_backups"

# Generate new content into zshrc_generated
{
  echo "# Generated by jds_config/zshrc/install.sh"
  echo "# Do not edit directly — edit the source files and run make install"
  echo ""
  cat "$PUBLIC"
  echo ""
  cat "$PRIVATE"
} > "$GENERATED"

# If no existing target, install directly
if [ ! -f "$TARGET" ]; then
  cp "$GENERATED" "$TARGET"
  echo "Generated ~/.zshrc from public + private sources"
  exit 0
fi

# Diff generated against current target
if diff -q "$GENERATED" "$TARGET" > /dev/null 2>&1; then
  echo "Generated ~/.zshrc from public + private sources"
  exit 0
fi

# Differences found — back up current target
mkdir -p "$BACKUP_DIR"
BACKUP_PATH="$BACKUP_DIR/zshrc_$(date +%Y-%m-%d_%H-%M-%S)"
cp "$TARGET" "$BACKUP_PATH"

# Deduplicate: if the previous backup is identical to the new one, remove the older one
PREV_BACKUP=$(ls -1t "$BACKUP_DIR" 2>/dev/null | grep -v "^$(basename "$BACKUP_PATH")$" | head -1)
if [ -n "$PREV_BACKUP" ] && diff -q "$BACKUP_PATH" "$BACKUP_DIR/$PREV_BACKUP" > /dev/null 2>&1; then
  rm "$BACKUP_DIR/$PREV_BACKUP"
fi

# Show the diff
echo "--- current ~/.zshrc"
echo "+++ new (generated)"
diff "$TARGET" "$GENERATED" || true

echo ""
echo "Differences found. Backup saved to $BACKUP_PATH."
printf "Proceed with install? [y/N] "
read -r REPLY

if [[ "$REPLY" =~ ^[Yy]$ ]]; then
  cp "$GENERATED" "$TARGET"
  echo "Generated ~/.zshrc from public + private sources"
else
  echo "Aborted. ~/.zshrc unchanged."
  exit 1
fi
