# Understanding the difference between .zprofile and .zshrc:
#  .zprofile: This file is executed only once when you log in to a new shell session. 
#             It's ideal for setting environment variables that need to be set only once per login.
#  .zshrc:    This file is executed every time you open a new terminal window or tab. It's suitable 
#             for setting environment variables or aliases that need to be applied to each new shell instance.


# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/jds/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/jds/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/jds/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/jds/google-cloud-sdk/completion.zsh.inc'; fi

# Claude bin path
export PATH="$HOME/.local/bin:$PATH"

# Personal scripts
export PATH="$HOME/bin:$PATH"

# ghostty
export PATH=/Applications/Ghostty.app/Contents/MacOS:$PATH




aliases() {
  alias | sort | awk -F"='|'$" '{printf "%-25s %s\n", $1, $2}'
}

### Aliases
alias mmtestbed='cd ~/workspace/django-schema-evaluation/django_schematic_many_megan_testbed'
alias schema='cd ~/workspace/django-schema-evaluation/django-schematic'
alias schema2='cd ~/workspace/django-schematic2'
alias ccds='cd ~/workspace/ccds-commonplace-book'
alias ccds-start-django='cd ~/workspace/ccds-commonplace-book/commonplace_book && make up'
alias ccds-start-react='cd ~/workspace/ccds-commonplace-book/frontend && npm start'
alias tt-claude='cd /Users/jds/workspace/tt-claude-tooling'
alias gh-claude='cd /Users/jds/workspace/gh-claude'
alias jds-config='cd /Users/jds/workspace/jds_config'
alias jds-p-config='cd /Users/jds/workspace/jds_private_config'



export HISTSIZE=10000  # Adjust the number to your desired history size
export SAVEHIST=10000


#export PYTEST_ADDOPTS="--reuse-db --capture=no --verbose"
#export PYTEST_ADDOPTS='-n 4 --reuse-db --capture=no --verbose -m "not perf"'


export PATH="/opt/homebrew/opt/libpq/bin:$PATH"

# >>> grok installer >>>
export PATH="$HOME/.grok/bin:$PATH"
fpath=(~/.grok/completions/zsh $fpath)
autoload -Uz compinit && compinit -C
# <<< grok installer <<<
# >>> ruby: Add rbenv to your shell (for zsh) >>>
eval "$(rbenv init - zsh)"
# <<< ruby: Add rbenv to your shell (for zsh) <<<

# All the time I want the path of a real file to hand to claude
cppath() {
    local full
    full=$(realpath "$1")
    if [[ "$full" == "$HOME"/* ]]; then
      echo "${full/#$HOME/~}" | pbcopy
      echo "Copied ${full/#$HOME/~} to your past buffer"
    else
      echo "$full" | pbcopy
      echo "Copied $full to your paste buffer"
    fi
  }


